import Image from "next/image";
import Link from "next/link";
import { ArrowDown,ArrowRight,Box,Boxes,Check,ChevronRight,FileCheck2,FoldHorizontal,Layers3,Menu,PackageCheck,PackageOpen,Palette,Printer,Recycle,ShieldCheck,Slice,SwatchBook } from "lucide-react";
import { DemoCTA } from "@/components/DemoCTA";
import { DemoNotice } from "@/components/DemoNotice";
import type { TemplateProduct } from "@/contracts/forgebase";
import { customPackagingData as data,packagingBase,productionSteps } from "../data";
import { PackConfigurator } from "./PackConfigurator";
import styles from "./Packaging.module.css";

const images={hero:`${packagingBase}/packaging-system-hero.png`,mailer:`${packagingBase}/corrugated-mailers.png`,carton:`${packagingBase}/folding-cartons.png`,rigid:`${packagingBase}/rigid-boxes.png`,prototype:`${packagingBase}/packaging-prototyping.png`};
const productImages:Record<string,string>={"ship-s1-mailer":images.mailer,"fold-f2-carton":images.carton,"present-r3-rigid-box":images.rigid};
const navigation=[{label:"Packaging",href:`${packagingBase}/products/`},{label:"Applications",href:`${packagingBase}/applications/`},{label:"Capabilities",href:`${packagingBase}/capabilities/`},{label:"Studio",href:`${packagingBase}/about/`}];
function cta(id:string){return data.ctas.find(item=>item.id===id)!}
function Brand(){return <Link href={`${packagingBase}/`} className={styles.brand} aria-label="Tuckform Packaging demo home"><span>T</span><b>TUCKFORM<small>PACKAGING / DEMO</small></b></Link>}
export function PackagingShell({children}:{children:React.ReactNode}){return <main className={styles.site}><DemoNotice message="Fictional custom packaging manufacturer. Structures, materials, print, MOQ, timelines and sustainability claims are illustrative; no request is transmitted."/><header className={styles.header}><Brand/><nav>{navigation.map(item=><Link key={item.href} href={item.href}>{item.label}</Link>)}</nav><DemoCTA cta={cta("packaging-nav-brief")} className={styles.headerCta}>Build a brief <ArrowRight/></DemoCTA><details className={styles.mobileNav}><summary aria-label="Open packaging site navigation"><Menu/></summary><div>{navigation.map(item=><Link key={item.href} href={item.href}>{item.label}</Link>)}<DemoCTA cta={cta("packaging-nav-brief")}>Build a brief</DemoCTA></div></details></header>{children}<footer className={styles.footer}><div><Brand/><p>{data.site.disclosure.message}</p></div><div><span>STUDIO MAP</span>{navigation.map(item=><Link key={item.href} href={item.href}>{item.label}</Link>)}</div><div><span>DEMO BOUNDARY</span><p>{data.site.legalNotice}. No order, production capability, certification or quoted price is represented.</p><Link href="/">Return to Template Lab</Link></div></footer></main>}
function PageIntro({code,title,description}:{code:string;title:string;description:string}){return <header className={styles.pageIntro}><div><span>{code}</span><h1>{title}</h1><p>{description}</p></div><div className={styles.paperShapes}><i/><i/><i/></div><ArrowDown/></header>}
function PackCard({product,index}:{product:TemplateProduct;index:number}){return <article className={styles.packCard}><div><Image src={productImages[product.slug]} alt={`Fictional custom packaging prototypes representing ${product.name}`} fill sizes="(max-width:800px) 100vw, 34vw"/></div><header><span>0{index+1}</span><b>{product.modelNumber}</b></header><h2>{product.name}</h2><p>{product.shortDescription}</p><DemoCTA cta={product.cta}>Open structure <ArrowRight/></DemoCTA></article>}

export function CustomPackagingTemplate(){return <PackagingShell><section className={styles.hero}><div className={styles.heroCopy}><span>CUSTOM STRUCTURE · PRINT · SAMPLE · REPEAT</span><h1>Flat idea.<br/><em>Repeatable pack.</em></h1><p>Connect product fit, structure, material, print and quantity before the first production decision.</p><div><DemoCTA cta={cta("packaging-configure")} className={styles.primaryButton}>Configure a pack <ArrowRight/></DemoCTA><DemoCTA cta={cta("packaging-systems")} className={styles.outlineButton}>View systems</DemoCTA></div></div><div className={styles.heroImage}><Image src={images.hero} alt="Fictional custom packaging system with corrugated mailer, folding carton, rigid box and flat dieline" fill priority sizes="(max-width:800px) 100vw, 58vw"/><span>STRUCTURE STUDIO / ILLUSTRATIVE</span></div><aside className={styles.heroNote}><b>Start flat.</b><p>Approve structure before print and volume.</p></aside></section><section className={styles.steps}>{productionSteps.map(step=><article key={step.code}><span>{step.code}</span><h2>{step.name}</h2><p>{step.text}</p></article>)}</section><section className={styles.homeConfig}><PackConfigurator submitCTA={cta("packaging-submit")} compact/></section><section className={styles.packSystems}><header><span>PACKAGING SYSTEMS / 02</span><h2>Three structures.<br/>Different production logic.</h2></header><div>{data.products.map((product,index)=><PackCard key={product.id} product={product} index={index}/>)}</div></section><section className={styles.prototypeFeature}><div><Image src={images.prototype} alt="Fictional packaging engineer reviewing a corrugated prototype beside a digital cutting table" fill sizes="(max-width:800px) 100vw, 52vw"/></div><article><span>SAMPLE PATH / 03</span><h2>Structure first.<br/>Color second.<br/>Approval visible.</h2><p>White samples, printed mocks and production approvals answer different questions. The site keeps those stages distinct.</p><DemoCTA cta={cta("packaging-sample")}>Request a structural sample <ArrowRight/></DemoCTA></article></section></PackagingShell>}

export function PackagingProductsPage(){return <PackagingShell><PageIntro code="PACKAGING SYSTEMS / 01" title="Choose the structure that matches the pack-out." description="Compare three fictional systems by board, printing, insert, MOQ and sample path before building a configuration brief."/><section className={styles.packIndex}>{data.products.map((product,index)=><PackCard key={product.id} product={product} index={index}/>)}</section><section className={styles.dielineBand}><Slice/><div><span>DIELINE BOUNDARY</span><h2>Static Demo, not a dieline generator.</h2><p>The production product needs a governed structure library or parametric dieline service before dimensions can generate manufacturing artwork.</p></div></section></PackagingShell>}
export function PackagingProductPage({product}:{product:TemplateProduct}){return <PackagingShell><div className={styles.breadcrumbs}><Link href={`${packagingBase}/products/`}>Packaging systems</Link><ChevronRight/><b>{product.name}</b></div><section className={styles.productHero}><div><span>{product.modelNumber}</span><h1>{product.name}</h1><p>{product.shortDescription}</p><DemoCTA cta={cta("packaging-configure")} className={styles.primaryButton}>Configure this system <ArrowRight/></DemoCTA></div><div><Image src={productImages[product.slug]} alt={`Fictional prototypes of ${product.name}`} fill priority sizes="(max-width:800px) 100vw, 55vw"/><span>DEMO STRUCTURE FAMILY</span></div></section><section className={styles.specBoard}><aside><span>PRODUCTION VARIABLES</span><h2>Every choice changes the handoff.</h2><p>All values are illustrative and require structural, print and manufacturing review.</p></aside><div>{product.attributes.map((attr,index)=><article key={attr.label}><b>0{index+1}</b><span>{attr.label}</span><h3>{attr.value}</h3></article>)}</div></section><section className={styles.packFit}>{product.applications?.map((app,index)=><article key={app}><span>FIT 0{index+1}</span><h3>{app}</h3><p>Confirm product geometry, distribution path and pack-out process.</p></article>)}</section></PackagingShell>}
export function PackagingApplicationsPage(){const icons=[PackageCheck,Box,Boxes];return <PackagingShell><PageIntro code="APPLICATIONS / 02" title="Design around the journey, not only the shelf." description="Each application starts with containment, handling and opening behavior before material or decoration choices."/><section className={styles.appCards}>{data.applications.map((app,index)=>{const Icon=icons[index];return <article key={app.id}><header><span>0{index+1}</span><Icon/></header><h2>{app.name}</h2><p>{app.description}</p><div><b>Carry into brief</b><small>{index===0?"Fragility · distribution · pack-out":index===1?"Shelf · filling · print hierarchy":"Components · sequence · kitting"}</small></div></article>})}</section><section className={styles.actionBand}><h2>Have a product envelope?</h2><DemoCTA cta={cta("packaging-configure")}>Configure the pack <ArrowRight/></DemoCTA></section></PackagingShell>}
export function PackagingCapabilitiesPage(){const icons=[FoldHorizontal,SwatchBook,Printer];return <PackagingShell><PageIntro code="CAPABILITIES / 03" title="From structural question to controlled repeat." description="Capability content follows the packaging approval path instead of presenting disconnected machine claims."/><section className={styles.capFlow}>{data.capabilities.map((cap,index)=>{const Icon=icons[index];return <article key={cap.id}><span>STEP 0{index+1}</span><Icon/><h2>{cap.name}</h2><p>{cap.description}</p><b>{cap.metrics?.[0].value}</b></article>})}</section><section className={styles.prototypeFeature}><div><Image src={images.prototype} alt="Fictional packaging prototype review in a clean sample room" fill sizes="(max-width:800px) 100vw, 52vw"/></div><article><span>PROOFING CONTEXT</span><h2>One sample cannot answer every question.</h2><ul><li><Check/>White sample: structure and pack-out</li><li><Check/>Color mock: hierarchy and print direction</li><li><Check/>Approval sample: governed production handoff</li></ul></article></section></PackagingShell>}
export function PackagingAboutPage(){return <PackagingShell><PageIntro code="STUDIO / 04" title="A packaging story built around repeatability." description="Tuckform Packaging is a fictional identity demonstrating how ForgeBase can connect creative packaging work to controlled production data."/><section className={styles.studioValues}>{[{icon:PackageOpen,title:"Open the structure",copy:"Make folds, inserts and pack-out assumptions visible before decoration."},{icon:Palette,title:"Separate proof questions",copy:"Use structural and color samples for the decisions they can actually support."},{icon:Layers3,title:"Protect the revision",copy:"Carry the approved dieline, artwork, substrate and packing instruction into repeat production."}].map((item,index)=>{const Icon=item.icon;return <article key={item.title}><span>0{index+1}</span><Icon/><h2>{item.title}</h2><p>{item.copy}</p></article>})}</section><section className={styles.disclosure}><ShieldCheck/><div><span>FICTIONAL STUDIO</span><h2>No real plant, customer, certification or production result is represented.</h2><p>{data.site.legalNotice}. Every image, capability, MOQ and schedule exists only for a realistic website test.</p></div></section><section className={styles.certCards}>{data.certifications.map(cert=><article key={cert.id}><FileCheck2/><h3>{cert.name}</h3><p>{cert.scope}</p><b>DEMO ONLY</b></article>)}</section></PackagingShell>}
export function PackagingRFQPage(){return <PackagingShell><PageIntro code="PACKAGING BRIEF / 05" title="Put structure, print and volume in the same conversation." description="Configure a fictional package and preview the context a production ForgeBase workflow could carry into structural review, sampling and quotation."/><PackConfigurator submitCTA={cta("packaging-submit")}/><section className={styles.noSend}><Recycle/><p>No quote, sample, lead, contact, CRM record or email is created by this static preview.</p></section></PackagingShell>}
