"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, Bell, CheckCircle2, ClipboardList, MailCheck, RefreshCw, UserRoundCheck } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { apiClient } from "@/lib/api/client";
import { useAuth } from "@/lib/auth/store";
type Stats={total:number;unassigned:number;awaiting_acceptance:number;overdue_acceptance:number;accepted:number};
type RFQ={id:string;rfq_number:string;status:string;priority:string;assigned_to_name:string|null;acceptance_sla_breached:boolean;created_at:string;contact:{full_name:string;company_name:string|null;country:string|null}|null};
type Queue={total_open:number};
const FLOW=[["內容準備","網站與產品準備","/dashboard/workspaces/website-product"],["觀察市場","訪客與來源觀察","/dashboard/workspaces/visitor-sources"],["辨識買家","買家與聯絡資料","/dashboard/workspaces/buyer-details"],["交給業務","詢價接手與分派","/dashboard/workspaces/inquiries"]] as const;
const status:Record<string,string>={new:"新進詢價",assigned:"已分派",accepted:"已接手"};
export default function DashboardPage(){
 const {state}=useAuth(),token=state.status==="authenticated"?state.accessToken:"",user=state.status==="authenticated"?state.user:null;
 const [stats,setStats]=useState<Stats|null>(null),[rfqs,setRfqs]=useState<RFQ[]>([]),[queue,setQueue]=useState<Queue|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!token)return;setLoading(true);setError(null);try{const r=await Promise.all([apiClient.get<Stats>("/tracking/rfqs/stats?days=30",token),apiClient.get<RFQ[]>("/tracking/rfqs?view=active&limit=12",token),apiClient.get<Queue>("/ops/task-queue",token)]);setStats(r[0]);setRfqs(r[1]);setQueue(r[2])}catch(e){setError(e instanceof Error?e.message:"營運資料載入失敗")}finally{setLoading(false)}},[token]);useEffect(()=>{void load()},[load]);
 const priorities=useMemo(()=>[...rfqs].filter(x=>x.status==="new"||x.status==="assigned").sort((a,b)=>Number(b.acceptance_sla_breached)-Number(a.acceptance_sla_breached)||Number(b.priority==="urgent")-Number(a.priority==="urgent")).slice(0,5),[rfqs]);
 const todo=queue?.total_open??0,stages=[["有效詢價",stats?.total??0],["等待分派",stats?.unassigned??0],["等待接手",stats?.awaiting_acceptance??0],["完成交接",stats?.accepted??0]] as const,max=Math.max(...stages.map(x=>x[1]),1);
 const metrics=[["今日必須完成",todo,"未分派、待接手與待核准",ClipboardList,"border-l-[#087b8f]"],["新詢價待分派",stats?.unassigned??"—","主管需指定負責業務",MailCheck,"border-l-amber-500"],["等待業務接手",stats?.awaiting_acceptance??"—",(stats?.overdue_acceptance??0)+" 筆已逾期",UserRoundCheck,"border-l-emerald-700"],["本月完成交接",stats?.accepted??"—","由業務後續處理",CheckCircle2,"border-l-violet-500"]] as const;
 return <div className="space-y-4 pb-8">
 <section className="rounded-[14px] bg-gradient-to-r from-[#123b55] to-[#087b8f] px-7 py-6 text-white shadow-[0_10px_28px_rgba(20,38,57,.08)]"><div className="flex flex-wrap items-center justify-between gap-5"><div><p className="text-[13px] font-extrabold text-cyan-100">今天先完成網站承接與詢價交接</p><h1 className="mt-1 text-[29px] font-black">{user?.full_name?user.full_name+"，":""}今天必須完成 {todo} 項</h1><p className="mt-2 text-[15px] text-cyan-50">{stats?.unassigned??0} 筆新詢價等待分派；先讓每筆有效需求交到正確業務手上。</p></div><div className="flex gap-2"><Button asChild className="h-11 bg-white text-[#087b8f] hover:bg-cyan-50"><Link href="/dashboard/tasks">開啟今日待辦 <ArrowRight className="ml-2 h-4 w-4"/></Link></Button><Button variant="outline" size="icon" className="h-11 border-white/40 bg-white/10 text-white hover:bg-white/20 hover:text-white" onClick={load} disabled={loading}><RefreshCw className={loading?"h-4 w-4 animate-spin":"h-4 w-4"}/></Button></div></div></section>
 {error&&<Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}
 <section className="rounded-[14px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-end justify-between gap-3"><div><h2 className="text-xl font-extrabold text-[#10263b]">外銷網站接單流程地圖</h2><p className="mt-1 text-sm text-slate-500">從網站與產品準備，看見市場訊號，到詢價交給業務；系統在業務接手後不取代 CRM。</p></div><Link href="/dashboard/workspaces/website-product" className="text-sm font-extrabold text-[#087b8f]">查看全部功能 →</Link></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{FLOW.map(([short,title,href],i)=><Link key={title} href={href} className="rounded-[10px] border border-slate-200 bg-slate-50 p-3 hover:border-[#8cbec7] hover:bg-cyan-50"><span className="text-xs font-black text-[#087b8f]">階段 {i+1}</span><p className="mt-1 font-extrabold text-[#10263b]">{short}</p><p className="mt-1 text-xs text-slate-500">{title}</p></Link>)}</div></section>
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,note,Icon,accent])=>{const I=Icon;return <article key={label} className={"min-h-32 rounded-[14px] border border-slate-200 border-l-4 bg-white p-5 shadow-sm "+accent}><div className="flex justify-between"><p className="text-sm font-bold text-slate-500">{label}</p><I className="h-5 w-5 text-[#087b8f]"/></div><p className="mt-4 text-4xl font-black text-[#10263b]">{value}</p><p className="mt-2 text-xs text-slate-500">{note}</p></article>})}</section>
 <section className="grid gap-4 xl:grid-cols-[minmax(0,1.65fr)_minmax(290px,.75fr)]"><article className="overflow-hidden rounded-[14px] border border-slate-200 bg-white shadow-sm"><header className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="text-xl font-extrabold text-[#10263b]">主管優先工作</h2><p className="mt-1 text-sm text-slate-500">依時效、緊急程度與收到時間排序</p></div><Link href="/dashboard/rfqs" className="text-sm font-extrabold text-[#087b8f]">查看全部待辦 →</Link></header><div className="px-4 py-1">{priorities.length?priorities.map((r,i)=><Link key={r.id} href={"/dashboard/rfqs/"+r.id} className="grid min-h-[76px] grid-cols-[48px_minmax(0,1fr)_auto] items-center gap-3 border-b px-1 py-3 last:border-0 hover:bg-slate-50"><span className="grid h-11 w-11 place-items-center rounded-lg bg-amber-50 text-xs font-black text-amber-700">{r.acceptance_sla_breached?"逾期":i===0?"優先":"待辦"}</span><span className="min-w-0"><strong className="block truncate text-[#10263b]">{r.contact?.company_name||r.contact?.full_name||"未填買家公司"}</strong><small className="mt-1 block truncate text-slate-500">{r.contact?.country||"地區未填"}・{r.rfq_number}・{status[r.status]||r.status}</small></span><span className="text-right"><small className={r.acceptance_sla_breached?"font-bold text-red-600":"font-bold text-[#176c58]"}>{!r.assigned_to_name?"詢價分派":r.acceptance_sla_breached?"接手逾期":"詢價接手"}</small><b className="mt-2 block rounded-lg border px-3 py-1.5 text-sm text-[#087b8f]">處理</b></span></Link>):<p className="py-12 text-center text-sm text-slate-500">目前沒有等待承接的詢價</p>}</div></article>
 <aside className="space-y-4"><article className="rounded-[14px] border bg-white shadow-sm"><header className="border-b px-5 py-4"><h2 className="text-lg font-extrabold text-[#10263b]">本月網站承接</h2><p className="mt-1 text-sm text-slate-500">網站訊號到業務交接</p></header><div className="space-y-3 p-5">{stages.map(([label,value])=><div key={label} className="grid grid-cols-[82px_1fr_28px] items-center gap-2 text-sm"><span>{label}</span><span className="h-2.5 overflow-hidden rounded-full bg-slate-100"><i className="block h-full rounded-full bg-[#247d69]" style={{width:Math.max(value?8:0,Math.round(value/max*100))+"%"}}/></span><b>{value}</b></div>)}<Button asChild variant="outline" className="mt-2 w-full"><Link href="/dashboard/rfqs">查看詢價交接</Link></Button></div></article><article className="rounded-[14px] border bg-white shadow-sm"><header className="border-b px-5 py-4"><h2 className="text-lg font-extrabold text-[#10263b]">建議下一步</h2></header><div className="space-y-3 p-4"><div className="border-l-[3px] border-[#087b8f] bg-[#f5fafb] p-3"><b>上午先完成分派</b><p className="mt-1 text-sm text-slate-500">{stats?.unassigned??0} 筆新詢價等待指定負責人與確認資料。</p></div><div className="border-l-[3px] border-[#087b8f] bg-[#f5fafb] p-3"><b>檢查等待接手案件</b><p className="mt-1 text-sm text-slate-500">{stats?.awaiting_acceptance??0} 筆已分派案件等待業務確認接手。</p></div></div></article></aside></section>
 <section><div className="mb-3 flex items-end justify-between"><div><h2 className="text-xl font-extrabold text-[#10263b]">今日工作的完整入口</h2><p className="mt-1 text-sm text-slate-500">功能不隱藏；每一項都清楚對應正式系統路由。</p></div><b className="text-sm">3 項</b></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[["01","每日營運總覽","掌握今日優先事項與近 30 天營運概況。","/dashboard"],["02","今日待辦","集中處理已指派、到期與逾期工作。","/dashboard/tasks"],["03","通知中心","查看系統與團隊需要留意的通知。","/dashboard/notifications"]].map(([no,title,body,href])=><Link key={no} href={href} className="min-h-44 rounded-[14px] border bg-white p-5 shadow-sm hover:border-[#8cbec7] hover:bg-[#f7fbfc]"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#e8f6f7] text-sm font-black text-[#087b8f]">{no}</span><h3 className="mt-4 font-extrabold text-[#10263b]">{title}</h3><p className="mt-2 text-sm text-slate-500">{body}</p><span className="mt-4 inline-block text-sm font-extrabold text-[#087b8f]">開啟功能 →</span></Link>)}</div></section>
 </div>
}
