import Image from "next/image";
import Link from "next/link";
import { ArrowDown,ArrowRight,Atom,Boxes,Check,ChevronRight,FileCheck2,FileText,Layers3,Menu,Microscope,Scale,ShieldCheck,Sparkles,Thermometer,Zap } from "lucide-react";
import { DemoCTA } from "@/components/DemoCTA";
import { DemoNotice } from "@/components/DemoNotice";
import type { TemplateCategory,TemplateProduct } from "@/contracts/forgebase";
import { engineeringMaterialsData as data,evidenceAxes,materialResources,materialsBase } from "../data";
import { MaterialLens } from "./MaterialLens";
import { SampleBrief } from "./SampleBrief";
import styles from "./Materials.module.css";

const images={archive:`${materialsBase}/material-archive-hero.png`,polymers:`${materialsBase}/performance-polymers.png`,alloys:`${materialsBase}/lightweight-alloys.png`,ceramics:`${materialsBase}/technical-ceramics.png`,lab:`${materialsBase}/materials-testing-lab.png`};
const familyImages:Record<string,string>={"cat-polymers":images.polymers,"cat-alloys":images.alloys,"cat-ceramics":images.ceramics};
const navigation=[{label:"Materials",href:`${materialsBase}/products/`},{label:"Applications",href:`${materialsBase}/applications/`},{label:"Evidence",href:`${materialsBase}/resources/`},{label:"Compliance",href:`${materialsBase}/certifications/`},{label:"About",href:`${materialsBase}/about/`}];
function cta(id:string){return data.ctas.find(item=>item.id===id)!}

function Brand(){return <Link href={`${materialsBase}/`} className={styles.brand} aria-label="Matera Materials demo home"><span><i/><i/><i/></span><b>MATERA<small>MATERIALS / DEMO</small></b></Link>}
export function MaterialsShell({children}:{children:React.ReactNode}){return <main className={styles.site}><DemoNotice message="Fictional engineering-material supplier. Grades, properties, documents, compliance and availability are illustrative; no request is transmitted."/><header className={styles.header}><Brand/><nav>{navigation.map(item=><Link key={item.href} href={item.href}>{item.label}</Link>)}</nav><DemoCTA cta={cta("materials-nav-sample")} className={styles.sampleCta}>Request sample <ArrowRight/></DemoCTA><details className={styles.mobileNav}><summary aria-label="Open materials site navigation"><Menu/></summary><div>{navigation.map(item=><Link key={item.href} href={item.href}>{item.label}</Link>)}<DemoCTA cta={cta("materials-nav-sample")}>Request sample</DemoCTA></div></details></header>{children}<footer className={styles.footer}><div><Brand/><p>{data.site.disclosure.message}</p></div><div><span>ARCHIVE</span>{navigation.slice(0,4).map(item=><Link key={item.href} href={item.href}>{item.label}</Link>)}</div><div><span>DEMO LIMIT</span><p>{data.site.legalNotice}. No grade, test, compliance or availability claim is made.</p><Link href="/">Return to Template Lab</Link></div></footer></main>}
function PageIntro({code,title,description}:{code:string;title:string;description:string}){return <header className={styles.pageIntro}><div><span>{code}</span><h1>{title}</h1><p>{description}</p></div><div className={styles.introAxis}><i/><i/><i/><i/></div><ArrowDown/></header>}
function FamilyCard({category,index}:{category:TemplateCategory;index:number}){const product=data.products.find(item=>item.categoryId===category.id)!;return <article className={styles.familyCard}><div><Image src={familyImages[category.id]} alt={`Fictional ${category.name} engineering material specimens`} fill sizes="(max-width:800px) 100vw, 33vw"/></div><header><span>FAMILY / 0{index+1}</span><b>{category.name}</b></header><p>{category.description}</p><dl>{product.attributes.slice(0,3).map(attr=><div key={attr.label}><dt>{attr.label}</dt><dd>{attr.value}</dd></div>)}</dl><Link href={`${materialsBase}/categories/${category.slug}/`}>Open material family <ArrowRight/></Link></article>}

export function EngineeringMaterialsTemplate(){return <MaterialsShell><section className={styles.hero}><div className={styles.heroTitle}><span>ENGINEERING MATERIALS / EVIDENCE ARCHIVE</span><h1>Choose by evidence.<br/><em>Not instinct.</em></h1><p>Translate temperature, load, exposure and processing constraints into a shortlist with visible test context.</p><div><DemoCTA cta={cta("materials-lens")} className={styles.primaryButton}>Open Material Lens <ArrowRight/></DemoCTA><DemoCTA cta={cta("materials-docs")} className={styles.paperButton}>Demo documents</DemoCTA></div></div><div className={styles.heroArchive}><Image src={images.archive} alt="Fictional archive of polymer, alloy, ceramic and composite engineering material specimens" fill priority sizes="100vw"/><span>SPECIMEN ARCHIVE / ILLUSTRATIVE</span><aside><b>03</b><small>Demo material families</small></aside></div><div className={styles.heroIndex}>{evidenceAxes.map((axis,index)=><article key={axis.key}><span>0{index+1}</span><b>{axis.label}</b><p>{axis.hint}</p></article>)}</div></section><section className={styles.homeLens}><MaterialLens products={data.products} embedded/></section><section className={styles.familySection}><header><div><span>MATERIAL FAMILIES / 02</span><h2>Compare distinct behavior,<br/>not interchangeable labels.</h2></div><p>Each family connects a tactile material story to normalized property records and a documented evidence boundary.</p></header><div>{data.categories.map((category,index)=><FamilyCard key={category.id} category={category} index={index}/>)}</div></section><section className={styles.labFeature}><div><Image src={images.lab} alt="Fictional materials engineer preparing a tensile-test specimen in a laboratory" fill sizes="(max-width:800px) 100vw, 52vw"/></div><article><span>TEST CONTEXT / 03</span><h2>A number without a method is not evidence.</h2><p>The production site should keep conditioning, orientation, units, test method and revision attached to every published property.</p><ul><li><Check/>Method and specimen context</li><li><Check/>Visible revision ownership</li><li><Check/>Demo claims kept separate from validation</li></ul><DemoCTA cta={cta("materials-docs")}>Review evidence records <ArrowRight/></DemoCTA></article></section></MaterialsShell>}

export function MaterialsProductsPage(){return <MaterialsShell><PageIntro code="MATERIAL LENS / 01" title="Select from conditions, not a memorized grade name." description="Adjust three decision axes to explore a fictional ranked shortlist, then inspect the property and evidence context behind each grade."/><MaterialLens products={data.products}/><section className={styles.gradeLedger}>{data.products.map((product,index)=><article key={product.id}><span>0{index+1}</span><h2>{product.name}</h2><p>{product.shortDescription}</p><DemoCTA cta={product.cta}>Open grade record <ArrowRight/></DemoCTA></article>)}</section></MaterialsShell>}

export function MaterialProductPage({product}:{product:TemplateProduct}){const category=data.categories.find(item=>item.id===product.categoryId)!;return <MaterialsShell><div className={styles.breadcrumbs}><Link href={`${materialsBase}/products/`}>Material Lens</Link><ChevronRight/><Link href={`${materialsBase}/categories/${category.slug}/`}>{category.name}</Link><ChevronRight/><b>{product.name}</b></div><section className={styles.gradeHero}><div><span>{product.modelNumber}</span><h1>{product.name}</h1><p>{product.shortDescription}</p><DemoCTA cta={cta("materials-nav-sample")} className={styles.primaryButton}>Request Demo sample <ArrowRight/></DemoCTA></div><div className={styles.gradeImage}><Image src={familyImages[category.id]} alt={`Fictional material specimens representing ${product.name}`} fill priority sizes="(max-width:800px) 100vw, 52vw"/><span>ILLUSTRATIVE GRADE FAMILY</span></div></section><section className={styles.propertySheet}><aside><span>PROPERTY RECORD</span><h2>Value, condition and boundary.</h2><p>Every number below is fictional. A production record requires an approved method, specimen state and revision.</p></aside><table><thead><tr><th>Property</th><th>Illustrative value</th><th>Evidence state</th></tr></thead><tbody>{product.attributes.map(attr=><tr key={attr.label}><th>{attr.label}</th><td>{attr.value}</td><td><i/>Demo only</td></tr>)}</tbody></table></section><section className={styles.fitGrid}><span>APPLICATION FIT / DISCUSSION ONLY</span>{product.applications?.map((app,index)=><article key={app}><b>0{index+1}</b><h3>{app}</h3><p>Confirm geometry, duration, environment and validation method before selection.</p></article>)}</section><section className={styles.recordNotice}><FileText/><div><span>CONTROLLED DOCUMENT PLACEHOLDER</span><h2>No TDS or SDS is downloaded.</h2><p>This route demonstrates where an approved grade document and revision would be resolved.</p></div><DemoCTA cta={cta("materials-docs")}>View Demo record</DemoCTA></section></MaterialsShell>}

export function MaterialCategoryPage({categorySlug}:{categorySlug:string}){const category=data.categories.find(item=>item.slug===categorySlug)!;const product=data.products.find(item=>item.categoryId===category.id)!;return <MaterialsShell><PageIntro code="MATERIAL FAMILY / 02" title={category.name} description={category.description??""}/><section className={styles.familyPortrait}><div><Image src={familyImages[category.id]} alt={`Fictional ${category.name} specimens arranged for technical selection`} fill priority sizes="(max-width:800px) 100vw, 55vw"/></div><article><span>{product.modelNumber}</span><h2>{product.name}</h2><p>{product.shortDescription}</p><dl>{product.attributes.map(attr=><div key={attr.label}><dt>{attr.label}</dt><dd>{attr.value}</dd></div>)}</dl><DemoCTA cta={product.cta}>Review grade evidence <ArrowRight/></DemoCTA></article></section><section className={styles.axisNotes}>{evidenceAxes.map((axis,index)=><article key={axis.key}><span>0{index+1}</span><h3>{axis.label}</h3><p>{axis.hint}</p></article>)}</section></MaterialsShell>}

export function MaterialsApplicationsPage(){const icons=[Thermometer,Scale,Zap];return <MaterialsShell><PageIntro code="APPLICATIONS / 03" title="Frame the exposure before the grade." description="Application pages organize selection questions around the operating environment and validation decision—not a generic industry label."/><section className={styles.appNotebook}>{data.applications.map((app,index)=>{const Icon=icons[index];return <article key={app.id}><header><span>CASE 0{index+1}</span><Icon/></header><h2>{app.name}</h2><p>{app.description}</p><div><small>QUESTIONS TO CARRY</small><ul><li>Duration and peak condition</li><li>Geometry and process state</li><li>Failure mode and validation</li></ul></div></article>})}</section><section className={styles.sampleBand}><div><span>NEED A PHYSICAL REVIEW?</span><h2>Carry the exposure into the sample brief.</h2></div><DemoCTA cta={cta("materials-consult")}>Discuss an application <ArrowRight/></DemoCTA></section></MaterialsShell>}

export function MaterialsResourcesPage(){return <MaterialsShell><PageIntro code="EVIDENCE LIBRARY / 04" title="Technical records with revision context." description="A document interface for property data, handling guidance and methods—without presenting fictional files as approved evidence."/><section className={styles.resourceLedger}>{materialResources.map(item=><article key={item.code}><FileText/><div><span>{item.code} / {item.type}</span><h2>{item.title}</h2><p>{item.note}</p></div><b>{item.revision}</b><DemoCTA cta={cta("materials-docs")}>Demo record <ArrowRight/></DemoCTA></article>)}</section><section className={styles.methodGrid}>{data.capabilities.map((cap,index)=><article key={cap.id}><span>0{index+1}</span><h3>{cap.name}</h3><p>{cap.description}</p><b>{cap.metrics?.[0].value}</b></article>)}</section></MaterialsShell>}

export function MaterialsCertificationsPage(){return <MaterialsShell><PageIntro code="COMPLIANCE / 05" title="Evidence status without invented assurance." description="Separate supplier declarations, test context and regulatory evidence while making every Demo boundary explicit."/><section className={styles.certLedger}>{data.certifications.map(cert=><article key={cert.id}><FileCheck2/><div><h2>{cert.name}</h2><p>{cert.scope}</p></div><span>ILLUSTRATIVE</span></article>)}</section><section className={styles.complianceNote}><ShieldCheck/><div><span>PRODUCTION RULE</span><h2>Publish only approved evidence with an owner and effective revision.</h2><p>This Demo does not represent RoHS, REACH, laboratory accreditation, certified properties or suitability for any application.</p></div></section></MaterialsShell>}

export function MaterialsAboutPage(){return <MaterialsShell><PageIntro code="ABOUT / 06" title="A material story built around decision quality." description="Matera Materials is a fictional supplier identity demonstrating how ForgeBase can support technical selection without pretending to be a real producer or laboratory."/><section className={styles.aboutPrinciples}>{[{icon:Layers3,title:"Context before comparison",copy:"Normalize the operating environment before comparing headline properties."},{icon:Microscope,title:"Method before claim",copy:"Keep specimen, condition, orientation and revision attached to every number."},{icon:Boxes,title:"Handoff with intent",copy:"Carry unresolved risks into technical support and physical sample review."}].map((item,index)=>{const Icon=item.icon;return <article key={item.title}><span>0{index+1}</span><Icon/><h2>{item.title}</h2><p>{item.copy}</p></article>})}</section><section className={styles.identityNotice}><Atom/><div><span>FICTIONAL IDENTITY</span><h2>No real company, facility, grade or laboratory is represented.</h2><p>{data.site.legalNotice}. All imagery and records exist only to support a realistic, safe website test.</p></div></section></MaterialsShell>}

export function MaterialsRFQPage(){return <MaterialsShell><PageIntro code="SAMPLE BRIEF / 07" title="Ask for a specimen with the decision attached." description="Preview how application conditions, a candidate grade and required supply form can stay together through a governed technical handoff."/><SampleBrief products={data.products} submitCTA={cta("materials-submit")}/><section className={styles.noSend}><Sparkles/><p>No sample, lead, contact, CRM record or email is created by this static preview.</p></section></MaterialsShell>}
